from __future__ import annotations

from typing import Protocol

from ..checkpoint import Checkpoint
from ..model import Event, MachineSnapshot


class Store(Protocol):
    """Persistence contract for durable AASM runs.

    Store implementations must append events in machine-local sequence order and
    atomically persist the derived snapshot with each event whenever possible.
    """

    def initialize_run(self, snapshot: MachineSnapshot) -> None: ...
    def append(self, machine_id: str, event: Event, snapshot: MachineSnapshot) -> Event: ...
    def load_snapshot(self, machine_id: str) -> MachineSnapshot: ...
    def load_events(self, machine_id: str, after_sequence: int = 0) -> list[Event]: ...
    def list_unfinished(self) -> list[str]: ...
    def save_checkpoint(self, machine_id: str, checkpoint: Checkpoint) -> None: ...
    def load_checkpoint(self, machine_id: str, checkpoint_id: str) -> Checkpoint: ...
    def close(self) -> None: ...
