from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class CodexGovernancePolicy:
    """Generate conservative Codex rules for common development operations.

    These rules are intentionally narrow. They reduce repeated approval review
    for read-only inspection and local verification while leaving destructive,
    credential, deployment, and unknown operations outside the allowlist.
    """

    allow_prefixes: list[list[str]] = field(default_factory=lambda: [
        ["git", "status"],
        ["git", "diff"],
        ["git", "log"],
        ["git", "show"],
        ["gh", "pr", "view"],
        ["gh", "pr", "list"],
        ["pytest"],
        ["python", "-m", "pytest"],
        ["python", "-m", "compileall"],
    ])
    forbid_prefixes: list[list[str]] = field(default_factory=lambda: [
        ["git", "reset", "--hard"],
        ["git", "clean", "-fd"],
        ["rm", "-rf", "/"],
    ])

    @staticmethod
    def _rule(pattern: list[str], decision: str, justification: str) -> str:
        values = ", ".join(repr(x) for x in pattern)
        return (
            "prefix_rule(\n"
            f"    pattern = [{values}],\n"
            f"    decision = {decision!r},\n"
            f"    justification = {justification!r},\n"
            ")\n"
        )

    def render_rules(self) -> str:
        blocks = [
            "# Generated by AASM. Review before installing.\n"
            "# This is a deterministic permission layer, not a sandbox bypass.\n"
        ]
        for prefix in self.allow_prefixes:
            blocks.append(self._rule(prefix, "allow", "Routine read-only/local verification action explicitly allowed by AASM policy."))
        for prefix in self.forbid_prefixes:
            blocks.append(self._rule(prefix, "forbid", "Destructive operation explicitly blocked by AASM policy."))
        return "\n".join(blocks)

    def render_requirements_toml(self) -> str:
        return (
            "# Generated AASM baseline. Review before deployment.\n"
            "allowed_sandbox_modes = [\"read-only\", \"workspace-write\"]\n\n"
            "# Keep network access constrained. Add only destinations required by the workflow.\n"
            "[experimental_network]\n"
            "enabled = true\n"
            "allow_local_binding = true\n"
        )
