from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class CodexGovernancePolicy:
    """Generate conservative Codex rules for common development operations.

    Rules here are specifically about commands that may need to run outside the
    sandbox. Therefore the default allowlist is intentionally read-only. Test,
    build, formatter, interpreter, package-manager, and arbitrary repo scripts
    are *not* auto-allowed outside the sandbox because they can execute project
    code with side effects. They should normally run inside workspace-write.
    """

    allow_prefixes: list[list[str]] = field(default_factory=lambda: [
        ["git", "status"],
        ["git", "diff"],
        ["git", "log"],
        ["git", "show"],
        ["gh", "pr", "view"],
        ["gh", "pr", "list"],
    ])
    forbid_prefixes: list[list[str]] = field(default_factory=lambda: [
        ["git", "reset", "--hard"],
        ["git", "clean"],
        ["rm", "-rf", "/"],
    ])

    @staticmethod
    def _rule(pattern: list[str], decision: str, justification: str) -> str:
        values = ", ".join(repr(x) for x in pattern)
        return (
            "prefix_rule(\n"
            f"    pattern = [{values}],\n"
            f"    decision = {decision!r},\n"
            f"    justification = {justification!r},\n"
            ")\n"
        )

    def render_rules(self) -> str:
        blocks = [
            "# Generated by AASM. Review before installing.\n"
            "# Rules reduce repeated approvals; they do not widen the sandbox.\n"
            "# Only read-only commands are allowed outside the sandbox by default.\n"
        ]
        for prefix in self.allow_prefixes:
            blocks.append(self._rule(prefix, "allow", "Read-only inspection explicitly allowed by AASM policy."))
        for prefix in self.forbid_prefixes:
            blocks.append(self._rule(prefix, "forbid", "Destructive operation explicitly blocked by AASM policy."))
        return "\n".join(blocks)

    def render_requirements_toml(self) -> str:
        # Fail closed: constrain sandbox modes and keep web search cached. Do not
        # enable the network proxy or add allowed domains implicitly; those are
        # environment-specific authority decisions.
        return (
            "# Generated AASM baseline. Review before deployment.\n"
            "allowed_sandbox_modes = [\"read-only\", \"workspace-write\"]\n"
            "allowed_web_search_modes = [\"cached\"]\n\n"
            "# Network proxy/domain exceptions are intentionally omitted.\n"
            "# Add only destinations explicitly required by the workflow.\n"
        )
