from __future__ import annotations


def html_document() -> str:
    return r'''<!doctype html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>AASM Control Center</title>
<style>
:root{color-scheme:dark;--bg:#080b10;--panel:#111823;--line:#273449;--text:#eef6ff;--muted:#91a1b8;--accent:#7dd3fc;--good:#86efac;--warn:#fde68a;--bad:#fca5a5}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at top,#14213a 0,var(--bg) 42%);color:var(--text);font:14px/1.45 system-ui}header{display:flex;justify-content:space-between;gap:16px;align-items:center;padding:22px 28px;border-bottom:1px solid var(--line);position:sticky;top:0;background:rgba(8,11,16,.93);backdrop-filter:blur(12px);z-index:2}h1{font-size:21px;margin:0}.sub{color:var(--muted)}main{max-width:1600px;margin:auto;padding:22px}.toolbar{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:16px}input,button,select{background:#0b111a;color:var(--text);border:1px solid var(--line);border-radius:9px;padding:9px 11px}input{min-width:250px}button{cursor:pointer}button:hover{border-color:var(--accent)}.danger{border-color:#7f1d1d}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.panel{background:linear-gradient(180deg,#141c29,#0e141e);border:1px solid var(--line);border-radius:15px;padding:15px;min-height:145px}.wide{grid-column:span 2}.full{grid-column:1/-1}h2{margin:0 0 12px;font-size:12px;letter-spacing:.13em;text-transform:uppercase;color:var(--muted)}.metric{font-size:27px;font-weight:750}.row{display:flex;justify-content:space-between;gap:12px;padding:7px 0;border-bottom:1px solid #1b2635}.row:last-child{border-bottom:0}.pill{border:1px solid var(--line);border-radius:999px;padding:4px 9px;color:var(--accent)}.good{color:var(--good)}.warning{color:var(--warn)}.bad{color:var(--bad)}pre{margin:0;white-space:pre-wrap;word-break:break-word;max-height:440px;overflow:auto;color:#d5e7ff}.scroll{max-height:380px;overflow:auto}.small{font-size:12px}.action{padding:4px 7px;min-width:0}.empty{color:var(--muted);padding:8px 0}@media(max-width:1200px){.grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:760px){.grid{grid-template-columns:1fr}.wide,.full{grid-column:auto}header{position:static;align-items:flex-start}.toolbar input{width:100%;min-width:0}}
</style></head>
<body><header><div><h1>AASM Control Center</h1><div class="sub">mission authority · effects · controlled forks · fleet · workers · logs · artifacts</div></div><span id="health" class="pill">offline</span></header>
<main><div class="toolbar"><input id="mid" placeholder="machine id"><input id="token" type="password" placeholder="bearer token"><button onclick="saveToken()">Save token</button><button onclick="loadDash()">Load</button><button onclick="missionPause('QUIESCE')">Quiesce</button><button onclick="missionPause('SUSPEND')" class="danger">Suspend</button><button onclick="missionResume()">Resume mission</button><button onclick="proposeFork()">Propose fork</button><button onclick="refresh()">Refresh</button></div>
<div class="grid">
<section class="panel"><h2>Mission</h2><div id="mission" class="metric">—</div><div class="row"><span>Pause mode</span><b id="missionmode">—</b></div><div class="row"><span>Event sequence</span><b id="sequence">—</b></div><div class="row"><span>State</span><b id="state">—</b></div><div id="goal" class="sub"></div></section>
<section class="panel"><h2>Effects</h2><div id="effectpending" class="metric">0</div><div class="sub">awaiting approval</div><div class="row"><span>Authorized</span><b id="effectauthorized">0</b></div><div class="row"><span>Running</span><b id="effectrunning">0</b></div><div class="row"><span>Unknown</span><b id="effectunknown">0</b></div><div class="row"><span>Failed</span><b id="effectfailed">0</b></div></section>
<section class="panel"><h2>Fleet</h2><div id="fleetlimit" class="metric">—</div><div class="sub">admission limit</div><div class="row"><span>Recommended</span><b id="recommended">—</b></div><div class="row"><span>Active leases</span><b id="activeleases">0</b></div><div class="row"><span>Workers</span><b id="workercount">0</b></div><div class="row"><span>Pending provision</span><b id="pendingprovision">0</b></div></section>
<section class="panel"><h2>Planner / Verification</h2><div id="teamstate" class="metric">—</div><div class="row"><span>Planner</span><b id="planner">—</b></div><div class="row"><span>Revision</span><b id="planrevision">—</b></div><div class="row"><span>Directive</span><b id="directive">—</b></div><div class="row"><span>Paused tasks</span><b id="pausedtasks">0</b></div></section>
<section class="panel wide"><h2>Pending and authorized effects</h2><div id="effects" class="scroll"></div></section>
<section class="panel wide"><h2>Workers</h2><div id="workers" class="scroll"></div></section>
<section class="panel wide"><h2>Active work</h2><div id="leases" class="scroll"></div></section>
<section class="panel wide"><h2>Forks</h2><div id="forks" class="scroll"></div></section>
<section class="panel wide"><h2>Telemetry</h2><div class="toolbar small"><button onclick="moreTelemetry()">Older telemetry</button></div><pre id="telemetry">—</pre></section>
<section class="panel wide"><h2>Artifacts</h2><div class="toolbar small"><button onclick="moreArtifacts()">Older artifacts</button></div><div id="artifacts" class="scroll"></div></section>
<section class="panel wide"><h2>Models</h2><div id="models"></div></section>
<section class="panel wide"><h2>Plan graph</h2><pre id="graph">—</pre></section>
<section class="panel full"><h2>Evidence and controls</h2><pre id="evidence">—</pre></section>
</div></main>
<script>
let current=null,last=null,telemetryCursor=null,artifactCursor=null,telemetryRows=[],artifactRows=[];const $=id=>document.getElementById(id);$('token').value=sessionStorage.getItem('aasmToken')||'';
function saveToken(){sessionStorage.setItem('aasmToken',$('token').value||'')}
function esc(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function api(path,opts={}){const token=$('token').value||sessionStorage.getItem('aasmToken')||'';opts.headers=Object.assign({'Accept':'application/json'},opts.headers||{},token?{'Authorization':'Bearer '+token}:{});const r=await fetch(path,opts);if(!r.ok)throw new Error(await r.text());return r.json()}
function body(value){return{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)}}
function rows(items,fn){return items.length?items.map(fn).join(''):'<div class="empty">None</div>'}
async function refresh(){try{const h=await api('/health');$('health').textContent=h.protocol+' · '+h.version}catch(e){$('health').textContent='offline'}if(current)await loadDash(false)}
async function loadDash(reset=true){saveToken();current=$('mid').value.trim();if(!current)return;if(reset){telemetryCursor=null;artifactCursor=null;telemetryRows=[];artifactRows=[]}const d=await api('/v1/machines/'+encodeURIComponent(current)+'/dashboard');last=d;render(d);if(reset){mergeTelemetry(d.telemetry_page||{});mergeArtifacts(d.artifact_page||{})}}
function render(d){const m=d.mission_control||{};$('mission').textContent=m.status||'RUNNING';$('mission').className=m.status==='PAUSED'?'metric warning':'metric good';$('missionmode').textContent=m.mode||'—';$('sequence').textContent=d.event_sequence??'—';$('state').textContent=d.state||'—';$('goal').textContent=d.problem?.goal||'';const q=d.effect_queue||{};$('effectpending').textContent=(q.pending_approval||[]).length;$('effectauthorized').textContent=(q.authorized||[]).length;$('effectrunning').textContent=(q.running||[]).length;$('effectunknown').textContent=(q.requires_reconciliation||[]).length;$('effectfailed').textContent=(q.failed||[]).length;const fc=d.fleet_control||{},collab=d.collaboration||{},leases=d.leases||[],workers=d.workers||[];$('fleetlimit').textContent=fc.admission_limit??'—';$('recommended').textContent=collab.recommended_workers??fc.last_refresh?.recommended_workers??'—';$('activeleases').textContent=leases.filter(x=>x.status==='ACTIVE').length;$('workercount').textContent=workers.length;$('pendingprovision').textContent=(d.provisioning?.pending_effects||[]).length;const t=d.team_protocol||{};$('teamstate').textContent=t.configured?(t.paused?'PAUSED':'ACTIVE'):'OFF';$('planner').textContent=t.planner_id||'—';$('planrevision').textContent=t.plan_revision??'—';$('directive').textContent=t.latest_decision?.directive||'—';$('pausedtasks').textContent=(d.change_control?.paused_tasks||[]).length;$('models').innerHTML=rows(d.models||[],m=>`<div class=row><span>${esc(m.model_id)}</span><b>${Math.round((Number(m.strength)||0)*100)}%</b></div>`);$('workers').innerHTML=rows(workers,w=>`<div class=row><span>${esc(w.worker_id)} <span class=sub>${esc(w.resource_id)}</span></span><span><b>${esc(w.status||'')}</b> <button class=action data-aasm-action="worker-control" data-worker="${esc(w.worker_id)}" data-control="DRAIN">Drain</button> <button class=action data-aasm-action="worker-control" data-worker="${esc(w.worker_id)}" data-control="RESUME">Resume</button> <button class=action data-aasm-action="worker-control" data-worker="${esc(w.worker_id)}" data-control="OFFLINE">Offline</button></span></div>`);$('leases').innerHTML=rows(leases.filter(x=>x.status==='ACTIVE'),l=>`<div class=row><span>${esc(l.task_id)} → ${esc(l.worker_id)}</span><b>${esc(l.status)}</b></div>`);renderEffects(q);renderForks(d.forks||{});$('graph').textContent=JSON.stringify(d.graph,null,2);$('evidence').textContent=JSON.stringify({change_control:d.change_control,checkpoint_triggers:d.checkpoint_triggers,fleet_control:d.fleet_control,governance:d.governance,team_protocol:d.team_protocol,execution_controls:d.execution_controls},null,2)}
function effectType(row){return row.spec?.effect_type||'unknown'}function effectId(row){return row.spec?.effect_id||''}
function renderEffects(q){const all=[...(q.pending_approval||[]),...(q.authorized||[]),...(q.running||[]),...(q.requires_reconciliation||[]),...(q.failed||[])];$('effects').innerHTML=rows(all,row=>{const status=row.status||'',id=effectId(row),type=effectType(row);let actions='';if(status==='PROPOSED')actions=`<button class=action data-aasm-action="approve-effect" data-effect="${esc(id)}">Approve</button>`;else if(status==='AUTHORIZED'&&type==='machine.fork')actions=`<button class=action data-aasm-action="execute-fork" data-effect="${esc(id)}">Execute fork</button>`;else if(status==='AUTHORIZED'&&type.startsWith('fleet.'))actions='<span class=sub>Execute through configured provisioner API</span>';else if(status==='UNKNOWN')actions='<span class=warning>Reconcile external outcome</span>';else if(status==='FAILED')actions='<span class=bad>Inspect and recreate/retry by policy</span>';return `<div class=row><span><b>${esc(type)}</b><br><span class=sub>${esc(id)}</span></span><span>${esc(status)} ${actions}</span></div>`})}
function renderForks(f){const items=[...(f.history||[])];$('forks').innerHTML=rows(items,row=>`<div class=row><span>${esc(row.request?.target_machine_id||'—')}<br><span class=sub>seq ${esc(row.request?.source_sequence)} · ${esc(row.request?.reason||'')}</span></span><b>${esc(row.status||'')}</b></div>`)}
function mergeTelemetry(page){telemetryCursor=page.next_cursor||null;const seen=new Set(telemetryRows.map(x=>x.record_id));for(const row of page.items||[])if(!seen.has(row.record_id)){telemetryRows.push(row);seen.add(row.record_id)}$('telemetry').textContent=JSON.stringify(telemetryRows,null,2)}
function mergeArtifacts(page){artifactCursor=page.next_cursor||null;const seen=new Set(artifactRows.map(x=>x.artifact_id||x.ref));for(const row of page.items||[])if(!seen.has(row.artifact_id||row.ref)){artifactRows.push(row);seen.add(row.artifact_id||row.ref)}$('artifacts').innerHTML=rows(artifactRows,row=>`<div class=row><span>${esc(row.name)}<br><span class=sub>${esc(row.ref)}</span></span><button class=action data-aasm-action="preview-artifact" data-backend="${esc(row.backend)}" data-ref="${esc(row.ref)}">Preview</button></div>`)}
async function moreTelemetry(){if(!current||!telemetryCursor)return;mergeTelemetry(await api('/v1/machines/'+encodeURIComponent(current)+'/telemetry/page?limit=50&cursor='+encodeURIComponent(telemetryCursor)))}
async function moreArtifacts(){if(!current||!artifactCursor)return;mergeArtifacts(await api('/v1/machines/'+encodeURIComponent(current)+'/artifacts/page?limit=50&cursor='+encodeURIComponent(artifactCursor)))}
async function previewArtifact(backend,ref){const value=await api('/v1/machines/'+encodeURIComponent(current)+'/artifacts/content?backend='+encodeURIComponent(backend)+'&ref='+encodeURIComponent(ref));alert(value.text+(value.truncated?'\n\n[preview truncated]':''))}
async function missionPause(mode){if(!current)return alert('Load a run first');const actor=prompt('Actor / authority','operator');if(!actor)return;const reason=prompt('Reason for '+mode.toLowerCase());if(!reason)return;await api('/v1/machines/'+encodeURIComponent(current)+'/mission-control/pause',body({actor,reason,mode}));await loadDash(false)}
async function missionResume(){if(!current)return alert('Load a run first');const actor=prompt('Actor / authority','operator');if(!actor)return;const reason=prompt('Reason for resume');if(!reason)return;await api('/v1/machines/'+encodeURIComponent(current)+'/mission-control/resume',body({actor,reason}));await loadDash(false)}
async function workerControl(worker,action){const actor=prompt('Actor / authority','operator');if(!actor)return;const reason=prompt('Reason for '+action.toLowerCase());if(!reason)return;await api('/v1/machines/'+encodeURIComponent(current)+'/workers/'+encodeURIComponent(worker)+'/control',body({control:{action,actor,reason}}));await loadDash(false)}
async function approveEffect(id){const actor=prompt('Approver','operator');if(!actor)return;const reason=prompt('Approval reason');if(!reason)return;await api('/v1/machines/'+encodeURIComponent(current)+'/effects/'+encodeURIComponent(id)+'/authorize',body({actor,reason}));await loadDash(false)}
async function executeFork(id){await api('/v1/machines/'+encodeURIComponent(current)+'/forks/'+encodeURIComponent(id)+'/execute',body({}));await loadDash(false)}
async function proposeFork(){if(!current||!last)return alert('Load a run first');const actor=prompt('Actor','operator');if(!actor)return;const reason=prompt('Reason for alternate history');if(!reason)return;const sequence=Number(prompt('Source event sequence',String(last.event_sequence||1)));if(!sequence)return;await api('/v1/machines/'+encodeURIComponent(current)+'/forks/propose',body({request:{source_sequence:sequence,actor,reason}}));await loadDash(false)}
document.addEventListener('click',event=>{const button=event.target.closest('button[data-aasm-action]');if(!button)return;const action=button.dataset.aasmAction;if(action==='worker-control')workerControl(button.dataset.worker,button.dataset.control);else if(action==='approve-effect')approveEffect(button.dataset.effect);else if(action==='execute-fork')executeFork(button.dataset.effect);else if(action==='preview-artifact')previewArtifact(button.dataset.backend,button.dataset.ref)});
refresh();setInterval(()=>{if(current)loadDash(false).catch(()=>{})},4000)
</script></body></html>'''
