from __future__ import annotations


def html_document() -> str:
    return r'''<!doctype html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>AASM Control Center</title>
<style>
:root{color-scheme:dark;--panel:#111722;--line:#263143;--text:#edf4ff;--muted:#91a0b5;--accent:#7dd3fc;--warn:#fde68a}*{box-sizing:border-box}body{margin:0;font:14px/1.45 system-ui;background:radial-gradient(circle at top,#142033 0,#0a0d12 45%);color:var(--text)}header{padding:22px 28px;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between}h1{font-size:20px;margin:0}.sub{color:var(--muted)}main{padding:22px;max-width:1500px;margin:auto}.toolbar{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:16px}input,button{background:#0c121b;color:var(--text);border:1px solid var(--line);border-radius:8px;padding:9px 11px}input{min-width:280px}button{cursor:pointer}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.panel{background:linear-gradient(180deg,#141b27,#0f151f);border:1px solid var(--line);border-radius:14px;padding:16px;min-height:150px}.wide{grid-column:span 2}.full{grid-column:1/-1}h2{font-size:13px;text-transform:uppercase;letter-spacing:.12em;color:var(--muted);margin:0 0 12px}.metric{font-size:28px;font-weight:700}.row{display:flex;justify-content:space-between;gap:12px;padding:7px 0;border-bottom:1px solid #1c2634}.pill{display:inline-block;border:1px solid var(--line);border-radius:999px;padding:3px 8px;color:var(--accent)}.warning{color:var(--warn)}pre{white-space:pre-wrap;word-break:break-word;margin:0;color:#cfe2ff;max-height:420px;overflow:auto}.bar{height:9px;background:#202b3b;border-radius:9px;overflow:hidden}.bar>i{display:block;height:100%;background:linear-gradient(90deg,#38bdf8,#a78bfa)}@media(max-width:950px){.grid{grid-template-columns:1fr}.wide,.full{grid-column:auto}input{min-width:0;width:100%}}
</style></head>
<body><header><div><h1>AASM Control Center</h1><div class="sub">Durable state · live telemetry · authority-gated provisioning · fleet admission · Planner/Builder/Verifier</div></div><span id="health" class="pill">offline</span></header>
<main><div class="toolbar"><input id="mid" placeholder="machine id"><input id="token" type="password" placeholder="bearer token (if configured)"><button onclick="saveToken()">Save token</button><button onclick="loadDash()">Load run</button><button onclick="sendInterrupt()">Steer / interrupt</button><button onclick="refresh()">Refresh</button></div>
<div class="grid">
<section class="panel"><h2>Run</h2><div id="state" class="metric">—</div><div id="goal" class="sub"></div><div class="row"><span>Version</span><b id="version">—</b></div><div class="row"><span>Frontier</span><b id="frontier">—</b></div></section>
<section class="panel"><h2>Automatic checkpoint</h2><div id="triggerstate" class="metric">—</div><div class="row"><span>Policy</span><b id="triggerpolicy">—</b></div><div class="row"><span>Last trigger</span><b id="triggerreason">—</b></div><div class="row"><span>Paused tasks</span><b id="pausedtasks">0</b></div><div class="row"><span>Remaining nodes</span><b id="remainingcount">0</b></div></section>
<section class="panel"><h2>Fleet admission</h2><div id="fleetlimit" class="metric">—</div><div class="sub">active lease limit</div><div class="row"><span>Enabled</span><b id="fleetenabled">NO</b></div><div class="row"><span>Enforced</span><b id="fleetenforced">NO</b></div><div class="row"><span>Recommendation</span><b id="fleetrecommended">—</b></div><div class="row"><span>Runnable tasks</span><b id="fleettasks">0</b></div></section>
<section class="panel"><h2>Live telemetry</h2><div id="telemetrycount" class="metric">0</div><div class="sub">durable records</div><div class="row"><span>Latest kind</span><b id="telemetrykind">—</b></div><div class="row"><span>Latest task</span><b id="telemetrytask">—</b></div><div class="row"><span>Observed classes</span><b id="durationclasses">0</b></div><div class="row"><span>Artifacts</span><b id="artifactcount">0</b></div></section>
<section class="panel"><h2>Provisioning</h2><div id="pendingprovision" class="metric">0</div><div class="sub">pending effects</div><div class="row"><span>Plans proposed</span><b id="provisionhistory">0</b></div><div class="row"><span>Executions</span><b id="provisionexec">0</b></div><div class="row"><span>Latest status</span><b id="provisionstatus">—</b></div><div class="row"><span>Provider action</span><b id="provisionaction">—</b></div></section>
<section class="panel"><h2>Collaboration</h2><div id="recommendedworkers" class="metric">—</div><div class="sub">recommended workers</div><div class="row"><span>Useful ceiling</span><b id="workerceiling">—</b></div><div class="row"><span>Parallel width</span><b id="parallelwidth">—</b></div><div class="row"><span>Critical path</span><b id="criticalpath">—</b></div><div class="row"><span>Schedulable</span><b id="schedulable">—</b></div></section>
<section class="panel"><h2>Economics</h2><div class="metric" id="cost">—</div><div id="coststatus" class="sub"></div><div class="row"><span>Total model tokens</span><b id="tokens">0</b></div><div class="row"><span>Governance token share</span><b id="govratio">0%</b></div><div class="bar"><i id="govbar" style="width:0%"></i></div></section>
<section class="panel"><h2>Planner / Builder / Verifier</h2><div id="teamstate" class="metric">—</div><div class="row"><span>Planner</span><b id="planner">—</b></div><div class="row"><span>Plan revision</span><b id="planrevision">—</b></div><div class="row"><span>Latest directive</span><b id="latestdirective">—</b></div><div class="row"><span>Verifier reports</span><b id="verifierreports">0</b></div></section>
<section class="panel wide"><h2>Active work</h2><div id="leases"></div></section><section class="panel"><h2>Workers</h2><div id="workers"></div></section><section class="panel wide"><h2>Recent telemetry</h2><pre id="telemetryrecent">—</pre></section><section class="panel"><h2>Artifacts</h2><pre id="artifacts">—</pre></section><section class="panel wide"><h2>Plan graph</h2><pre id="graph">—</pre></section><section class="panel full"><h2>Evidence / controls</h2><pre id="evidence">—</pre></section></div></main>
<script>
let current=null;const $=id=>document.getElementById(id);$('token').value=sessionStorage.getItem('aasmToken')||'';function saveToken(){sessionStorage.setItem('aasmToken',$('token').value||'')}
function esc(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function api(path,opts={}){const token=$('token').value||sessionStorage.getItem('aasmToken')||'';opts.headers=Object.assign({},opts.headers||{},token?{'Authorization':'Bearer '+token}:{});const r=await fetch(path,opts);if(!r.ok)throw new Error(await r.text());return r.json()}
async function refresh(){try{const h=await api('/health');$('health').textContent=h.protocol||'online'}catch(e){$('health').textContent='offline'}if(current)await loadDash()}
function rows(items,fn){return items.length?items.map(fn).join(''):'<div class="sub">None</div>'}
async function loadDash(){saveToken();current=$('mid').value.trim();if(!current)return;const d=await api('/v1/machines/'+encodeURIComponent(current)+'/dashboard');$('state').textContent=d.state;$('goal').textContent=d.problem?.goal||'';$('version').textContent=d.version;$('frontier').textContent=(d.frontier||[]).length;
const cc=d.change_control||{},impact=cc.last_impact||{},tr=d.checkpoint_triggers||{},lasttr=tr.last||{};$('triggerstate').textContent=lasttr.triggered?'TRIGGERED':'CLEAR';$('triggerstate').className=lasttr.triggered?'metric warning':'metric';$('triggerpolicy').textContent=tr.policy?.enabled===false?'OFF':'ON';$('triggerreason').textContent=lasttr.reason||'—';$('pausedtasks').textContent=(cc.paused_tasks||[]).length;$('remainingcount').textContent=(impact.remaining_nodes||[]).length;
const fc=d.fleet_control||{},fr=fc.last_refresh||{};$('fleetlimit').textContent=fc.admission_limit??'—';$('fleetenabled').textContent=fc.policy?.enabled?'YES':'NO';$('fleetenforced').textContent=fr.enforced?'YES':'NO';$('fleetrecommended').textContent=fr.recommended_workers??'—';$('fleettasks').textContent=(fr.task_ids||[]).length;
const t=d.execution_telemetry||{},latest=t.latest||{},stats=t.duration_stats||{};$('telemetrycount').textContent=t.records||0;$('telemetrykind').textContent=latest.kind||'—';$('telemetrytask').textContent=latest.task_id||'—';$('durationclasses').textContent=Object.keys(stats.by_task_class||{}).length;$('artifactcount').textContent=(t.artifacts||[]).length;$('telemetryrecent').textContent=JSON.stringify((t.recent||[]).slice(-20),null,2);$('artifacts').textContent=JSON.stringify(t.artifacts||[],null,2);
const p=d.provisioning||{},pending=p.pending_effects||[],execs=p.executions||[],hist=p.history||[],latestExec=execs[execs.length-1]||{},latestPending=pending[pending.length-1]||{};$('pendingprovision').textContent=pending.length;$('provisionhistory').textContent=hist.length;$('provisionexec').textContent=execs.length;$('provisionstatus').textContent=latestExec.status||latestPending.status||'—';$('provisionaction').textContent=latestExec.action||latestPending.effect_type||'—';
const c=d.collaboration||{};$('recommendedworkers').textContent=c.recommended_workers??'—';$('workerceiling').textContent=c.useful_worker_ceiling??'—';$('parallelwidth').textContent=c.max_parallel_width??'—';$('criticalpath').textContent=c.critical_path==null?'—':Number(c.critical_path).toFixed(2);$('schedulable').textContent=c.schedulable_fraction==null?'—':Math.round(Number(c.schedulable_fraction)*100)+'%';
const e=d.economics||{};const amount='$'+Number(e.estimated_cost||0).toFixed(4);$('cost').textContent=e.cost_complete===false?amount+' + unpriced':amount;$('coststatus').textContent=e.cost_complete===false?`${Number(e.unpriced_tokens||0).toLocaleString()} tokens unpriced`:'priced usage complete';$('tokens').textContent=(e.tokens||0).toLocaleString();const g=Math.round((e.governance_token_ratio||0)*100);$('govratio').textContent=g+'%';$('govbar').style.width=Math.max(0,Math.min(100,g))+'%';
const team=d.team_protocol||{};$('teamstate').textContent=team.configured?(team.paused?'PAUSED':'ACTIVE'):'OFF';$('teamstate').className=team.paused?'metric warning':'metric';$('planner').textContent=team.planner_id||'—';$('planrevision').textContent=team.plan_revision??'—';$('latestdirective').textContent=team.latest_decision?.directive||'—';$('verifierreports').textContent=team.verifier_reports||0;$('workers').innerHTML=rows(d.workers||[],w=>`<div class=row><span>${esc(w.worker_id)}</span><b>${esc(w.status||'')}</b></div>`);$('leases').innerHTML=rows((d.leases||[]).filter(x=>x.status==='ACTIVE'),l=>`<div class=row><span>${esc(l.task_id)} → ${esc(l.worker_id)}</span><b>${esc(l.status)}</b></div>`);$('graph').textContent=JSON.stringify(d.graph,null,2);$('evidence').textContent=JSON.stringify({change_control:d.change_control,checkpoint_triggers:d.checkpoint_triggers,fleet_control:d.fleet_control,provisioning:d.provisioning,execution_telemetry:d.execution_telemetry,governance:d.governance,team_protocol:d.team_protocol,collaboration:d.collaboration,evidence:d.evidence},null,2)}
async function sendInterrupt(){if(!current)return alert('Load a run first');const note=prompt('Steering instruction / interrupt');if(!note)return;await api('/v1/machines/'+encodeURIComponent(current)+'/interrupt',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({note})});await loadDash()}refresh();setInterval(()=>{if(current)loadDash().catch(()=>{})},3000)
</script></body></html>'''
