from __future__ import annotations

from typing import Any

from ._epistemic_debt import (
    EPISTEMIC_DEBT_CLASSES,
    EPISTEMIC_DEBT_CONTRACT_ID,
    EPISTEMIC_DEBT_CONTRACT_VERSION,
    EPISTEMIC_DEBT_STABILITY,
    EpistemicDebtItem,
    EpistemicDebtProjection,
    project_epistemic_debt,
    validate_epistemic_debt_projection,
)
from ._manual_override import (
    MANUAL_OVERRIDE_ASSESSMENT_CONTRACT_ID,
    MANUAL_OVERRIDE_ASSESSMENT_CONTRACT_VERSION,
    MANUAL_OVERRIDE_ASSESSMENT_STATUSES,
    MANUAL_OVERRIDE_CONTRACT_ID,
    MANUAL_OVERRIDE_CONTRACT_VERSION,
    MANUAL_OVERRIDE_STABILITY,
    ManualOverride,
    ManualOverrideAssessment,
    OverrideValidityWindow,
    ResultingObligationRef,
    bind_manual_override,
    evaluate_manual_override,
)


def epistemic_debt_manual_override_contract() -> dict[str, Any]:
    return {
        "epistemic_debt_contract_id": EPISTEMIC_DEBT_CONTRACT_ID,
        "epistemic_debt_contract_version": EPISTEMIC_DEBT_CONTRACT_VERSION,
        "manual_override_contract_id": MANUAL_OVERRIDE_CONTRACT_ID,
        "manual_override_contract_version": MANUAL_OVERRIDE_CONTRACT_VERSION,
        "manual_override_assessment_contract_id": MANUAL_OVERRIDE_ASSESSMENT_CONTRACT_ID,
        "manual_override_assessment_contract_version": MANUAL_OVERRIDE_ASSESSMENT_CONTRACT_VERSION,
        "stability": EPISTEMIC_DEBT_STABILITY,
        "debt_source": "EXACT_EXISTING_AASM_CALCULUS_V1_OBLIGATIONS_AND_REQUIRES_EDGES_ONLY",
        "debt_graph": "NONE_SECONDARY_OR_PARALLEL",
        "debt_store": "NONE_SECONDARY_OR_PARALLEL",
        "debt_identity": "PROJECTION_OF_EXISTING_OBLIGATION_ID_AND_S4_7_SEMANTIC_FINGERPRINT",
        "debt_classes": list(EPISTEMIC_DEBT_CLASSES),
        "debt_scalar_score": "NONE",
        "debt_forgiveness": "NONE",
        "resource_scarcity_relation": "CANNOT_ERASE_OR_DOWNGRADE_EPISTEMIC_DEBT",
        "objective_relation": "CANNOT_OVERRIDE_OUTSTANDING_OR_TERMINAL_UNRESOLVED_OBLIGATIONS",
        "manual_override_target": "EXACT_EXISTING_AASM_RULE_V1_REVISION_AND_FINGERPRINT",
        "hard_floor_override": "FORBIDDEN_UNCONDITIONALLY",
        "rule_waiver_policy": "EXACT_RULE_CONTROL_POLICY_EXPLICIT_AUTHORIZED_REQUIRED",
        "authority_reference": "EXACT_EXISTING_SCOPED_AUTHORITY_REFERENCE_AND_EVIDENCE_ONLY_NOT_AUTHORITY_PROOF",
        "authority_revalidation": "REQUIRED_AT_POINT_OF_USE_BY_EXISTING_AUTHORITY_PLANE",
        "accepted_risk": "EXACT_EXISTING_RISK_ASSESSMENT_REQUIRES_EXPLICIT_ACCEPTANCE_ONLY",
        "duration": "EXPLICIT_CLOCK_ID_AND_BOUNDED_INTEGER_SEQUENCE_WINDOW_NO_HIDDEN_WALL_CLOCK",
        "resulting_obligations": "EXACT_EXISTING_CALCULUS_OBLIGATION_REFERENCES_ONLY_NO_SECOND_OBLIGATION_STORE",
        "append_only_history": "OVERRIDE_RECORD_NEVER_DELETES_OR_REWRITES_PRIOR_HISTORY",
        "assessment_is_waiver": False,
        "assessment_is_authorization": False,
        "assessment_grants_effect_authority": False,
        "assessment_mutates_rule": False,
        "assessment_mutates_obligation": False,
        "assessment_activates_current_override": False,
        "parallel_override_registry": "NONE",
        "current_override_pointer": "NONE",
        "parallel_authority_evaluator": "NONE",
        "parallel_risk_plane": "NONE",
        "runtime_admission": "PRE_ADMISSION_ONLY",
        "public_admission": "PRE_ADMISSION_ONLY",
    }


__all__ = [
    "EPISTEMIC_DEBT_CONTRACT_ID",
    "EPISTEMIC_DEBT_CONTRACT_VERSION",
    "EPISTEMIC_DEBT_STABILITY",
    "EPISTEMIC_DEBT_CLASSES",
    "MANUAL_OVERRIDE_CONTRACT_ID",
    "MANUAL_OVERRIDE_CONTRACT_VERSION",
    "MANUAL_OVERRIDE_ASSESSMENT_CONTRACT_ID",
    "MANUAL_OVERRIDE_ASSESSMENT_CONTRACT_VERSION",
    "MANUAL_OVERRIDE_STABILITY",
    "MANUAL_OVERRIDE_ASSESSMENT_STATUSES",
    "EpistemicDebtItem",
    "EpistemicDebtProjection",
    "OverrideValidityWindow",
    "ResultingObligationRef",
    "ManualOverride",
    "ManualOverrideAssessment",
    "project_epistemic_debt",
    "validate_epistemic_debt_projection",
    "bind_manual_override",
    "evaluate_manual_override",
    "epistemic_debt_manual_override_contract",
]
