SOLVER_LOOP_CONTRACT_ID="aasm.solver.loop.v1"
SOLVER_LOOP_CONTRACT_VERSION="0.1.0"
PHASES=("FRONTIER","OBLIGATION","REUSE","CAPABILITY_ROUTE","EXECUTE","VERIFY","ADMIT","TRUTH_MAINTENANCE","MEMORY","LEARN","CHECK_COMPLETION")

def solver_loop_contract():
    return {"contract_id":SOLVER_LOOP_CONTRACT_ID,"contract_version":SOLVER_LOOP_CONTRACT_VERSION,"phases":list(PHASES),"authority":"EXISTING_AASM_PATHS_ONLY"}
